CREATE TABLE IF NOT EXISTS tadada_auth (
    uid INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	userid INTEGER UNSIGNED NOT NULL,
	time INTEGER UNSIGNED NOT NULL DEFAULT 0,
	started INTEGER UNSIGNED NOT NULL DEFAULT 0,
    duration INTEGER UNSIGNED NOT NULL default 0,
	confirmed INTEGER(1) UNSIGNED NOT NULL DEFAULT 0,
	auth CHAR(255) NOT NULL DEFAULT '',
    remotehost VARCHAR(256) NOT NULL DEFAULT '',
    remoteip VARCHAR(40) NOT NULL DEFAULT '',
    useragent VARCHAR(100) NOT NULL DEFAULT '',
    share INT(1) UNSIGNED NOT NULL DEFAULT 0,
    urlid CHAR(40) NOT NULL DEFAULT '',
    url TEXT NOT NULL DEFAULT '',
    comment CHAR(140) NOT NULL DEFAULT '',
    INDEX (auth, userid, urlid) USING BTREE
);